she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('story/<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name = 'newsStory'),
    path('user-list/', views.userList.as_view(), name = 'userList'),
    path('user-story/<str:username>/', views.userStory.as_view(), name = 'userStory'),
    path('edit/<int:pk>/', views.StoryViewEdit.as_view(), name='userStoryEdit'),
    path('delete/<int:pk>/', views.StoryViewDelete.as_view(), name='userStoryDelete'),
    # path('category/<str:category_type>/', views.categoryStoryView.as_view(), name = 'categoryStory'),
    path('filter/', views.StoryFilterView.as_view(), name = 'filter'),

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('create-account/', views.CreateAccountView.as_view(), name ='createAccount'),
    path('profile/<str:username>/', views.UserProfileView.as_view(), name ='profile'),
    path('profile/edit/<str:username>/', views.UserProfileEditView.as_view(), name ='profileEdit'),

]

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Sooty's Blog</title>
        <meta name="description" content="">
        <meta name="author" content="Samara Love">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>Sooty's Blog</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock %} 
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if user.is_authenticated %}
        <a href="{% url 'users:profile' user.username %}">{{ user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:createAccount' %}">Create Account</a>
    {% endif %}
</nav>