she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('story/<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name = 'newsStory'),
    path('user-list/', views.userList.as_view(), name = 'userList'),
    path('user-story/<str:username>/', views.userStory.as_view(), name = 'userStory'),
    path('edit/<int:pk>/', views.StoryViewEdit.as_view(), name='userStoryEdit'),
    path('delete/<int:pk>/', views.StoryViewDelete.as_view(), name='userStoryDelete'),
    # path('category/<str:category_type>/', views.categoryStoryView.as_view(), name = 'categoryStory'),
    path('filter/', views.StoryFilterView.as_view(), name = 'filter'),

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('create-account/', views.CreateAccountView.as_view(), name ='createAccount'),
    path('profile/<str:username>/', views.UserProfileView.as_view(), name ='profile'),
    path('profile/edit/<str:username>/', views.UserProfileEditView.as_view(), name ='profileEdit'),

]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models


class NewsStory(models.Model):

    CHOICES = (
    ('About', 'About'),
    ('Adventures', 'Adventures'),
    ('Friends', 'Friends'),
    ('Family', 'Family'),
    # ('No Category Assigned', 'No Category Assigned'),
    )

    category = models.CharField(max_length=60, blank=True, default='No Category Assigned',choices=CHOICES,verbose_name="category")

    
    title = models.CharField(max_length=200)
    # author = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete = models.CASCADE,
        related_name="stories"
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_link = models.URLField(default = "", max_length=400)


    # def __str__(self):
    #     return self.title

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm, SplitDateTimeField, SplitDateTimeWidget
from .models import NewsStory

class StoryForm(ModelForm):
    image_link = forms.URLField(required=False)
    # ,help_text='Enter URL to a direct image. Otherwise, a random image will be chosen for you')
            
    pub_date = SplitDateTimeField(
		# use split date time field to allow the user to input both date and time
        widget=SplitDateTimeWidget(
        #    'class'="form-item",
			# we use the split date time widget to specify how the html gets built
            date_attrs={'type': 'date', 'class': "form-item", 'id': 'form-date'},
			# type date tells django to use the HTML5 date input
            time_attrs={'type': 'time', 'class': "form-item", 'id': 'form-time'},
			# type time tells django to use the HTML5 time input
            # default=timezone.now
        )
    )

    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content','image_link', 'category']
        widgets = {

            'title': forms.TextInput(
                attrs={'size': 10, 
                'id': 'form-title',
                'class': "form-item",
                'placeholder': 'Enter a catchy title',}
                ),
            # 'author': forms.TextInput(attrs={'size': 10,  'id': 'form-author','class': "form-item",'placeholder': 'Your name',}
            # ),
            'content': forms.Textarea(attrs={'size': 10,  'id': 'form-content','class': "form-item",'placeholder': 'Enter a rivoting story',}
            ),
            'image_link': forms.TextInput(attrs={'size': 10, 'id': 'form-link','class': "form-item",'placeholder': 'Enter URL to a direct image. Otherwise, a random image will be chosen for you',},),
            # forces you to upload with url
            # want to verify it exists. Django automatically does this 
        }

    # def delete(self, request, *args, **kwargs):
    #     """If DB Integrity Error, display msg and redirect to list"""
    #     try:
    #         return(super().delete(request, *args, **kwargs))
    #     except IntegrityError:
    #         messages.error(request, "Cannot be deleted")
    #         return render(request, template_name=self.template_name, context=self.get_context_data())

class UpdateStoryForm(ModelForm):
    image_link = forms.URLField(required=False)
    
    pub_date = SplitDateTimeField(
		# use split date time field to allow the user to input both date and time
        widget=SplitDateTimeWidget(
        #    'class'="form-item",
			# we use the split date time widget to specify how the html gets built
            date_attrs={'type': 'date', 'class': "form-item", 'id': 'form-date'},
			# type date tells django to use the HTML5 date input
            time_attrs={'type': 'time', 'class': "form-item", 'id': 'form-time'},
			# type time tells django to use the HTML5 time input
            # default=timezone.now
        )
    )

    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content','image_link','category']
        widgets = {

            'title': forms.TextInput(
                attrs={'size': 10, 
                'id': 'form-title',
                'class': "form-item",
                'placeholder': 'Enter a catchy title',}
                ),
            # 'author': forms.TextInput(attrs={'size': 10,  'id': 'form-author','class': "form-item",'placeholder': 'Your name',}
            # ),
            'content': forms.Textarea(attrs={'size': 10,  'id': 'form-content','class': "form-item",'placeholder': 'Enter a rivoting story',}
            ),
            'image_link': forms.TextInput(attrs={'size': 10, 'id': 'form-link','class': "form-item",'placeholder': 'Enter URL to a direct image. Otherwise, a random image will be chosen for you',})            
        }
    # def save(self, commit=True):
    #     user = super().save(commit=False)
    #     user.set_password(self.cleaned_data["password1"])
    #     if commit:
    #         user.save()
    #     return user
    

class DeleteStoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = []
    
    def delete(self, request, *args, **kwargs):
        """If DB Integrity Error, display msg and redirect to list"""
        try:
            return(super().delete(request, *args, **kwargs))
        except IntegrityError:
            messages.error(request, "Cannot be deleted")
            return render(request, template_name=self.template_name, context=self.get_context_data())



    # def delete(request, *args, **kwargs):
    #     self.object = self.get_object()
    #     # if self.object.gameteams_set.exists():
    #         # Return the appropriate response
    #     success_url = self.get_success_url()
    #     self.object.delete()
    #     return HttpResponseRedirect(success_url)


# class UploadFileForm(forms.Form):
#     title = forms.CharField(max_length=50)
#     file = forms.FileField()

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm, UpdateStoryForm, DeleteStoryForm
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.views import generic
from django.db.models import Count, F, Value

User = get_user_model()

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url =reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class IndexView(generic.ListView):
    template_name = 'news/index.html'
    
    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()        

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        # context['all_stories'] = NewsStory.objects.all().order_by('-category_type')
        context['all_users'] = User.objects.all().order_by('username')
        return context

class StoryFilterView(generic.ListView):
    template_name = 'news/filter.html'
    context_object_name = 'all_stories'

    def get_queryset(self):
        '''Return all news stories.'''
        qs = NewsStory.objects.all()   
        q = self.request.GET.get("category")
        if q: 
            qs = qs.filter(category=q)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = StoryForm
        # print(context)
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class userList(generic.ListView):
    model = User
    template_name = 'news/user-list.html'

class userStory(generic.DetailView):
    model = User
    template_name = 'news/user-story.html'

    slug_field = "username"
    slug_url_kwarg = "username"
    success_url =reverse_lazy('users:profile')


class categoryStoryView(generic.DetailView):
    pass
    # model = NewsStory
    # template_name = 'news/category.html'
    # context_object_name = 'story'

    # slug_field = "category_type"
    # slug_url_kwarg = "category_type"

#     @property
#    def total_number(self):
#        return self.category_type.all().count()

class StoryViewEdit(generic.edit.UpdateView):
    form_class = UpdateStoryForm
    context_object_name = 'storyForm'

    model = NewsStory
    template_name = 'news/edit.html'
    context_object_name = 'story'

    success_url =reverse_lazy('news:index')

class StoryViewDelete(generic.edit.DeleteView):
    form_class = DeleteStoryForm
    context_object_name = 'storyForm'

    model = NewsStory
    template_name = 'news/delete.html'
    context_object_name = 'story'

    success_url =reverse_lazy('news:index')

    # def post(self, request, *args, **kwargs):
    #     form = self.form_class(request.POST)
    #     if form.is_valid():
    #         form.delete()
    #         return redirect('news:index')

    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     return super().form_valid(form)

    # def post(self, request, *args, **kwargs):
    #     object = get_object_or_404(NewsStory, author=self.kwargs.get("author"))
    #     if request.method == 'POST':
    #         form = self.form_class(request.POST, instance=order)
    #         if form.is_valid():
    #             form.save()
    #             return redirect('news:story')
    #     else:
    #         form = PostForm(instance=post)
    #     return render(request, self.template_name, {'form': form})


# https://samulinatri.com/blog/django-modelform-tutorial/
            # form = PostForm(request.POST)



    # def my_view(request):
    #     # form = StoryForm
    #     return render_response('news/index.html',{'form': form})

she_codes_news/news/templates/news/category.html
{% extends "base.html" %}
{% load static %}    

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}



<div id="all-stories">
    <p>Category: {{story.category_type}}<br>
        There are {{story.Category_CHOICES|length}} categories. <br>
        {{story.choice_type|length}} stories have been categorised as {{story.category_type}}<br>
        Title: {{object.title}}
        category_type: {{object.category_type}}
    </p><br><br>


    {{stories.all|length}}

        {% for category in story.Category_CHOICES %}
            {{story.category_type}}
        {% endfor %}

    {% for category in story.Category_CHOICES %}
        {{category}}
    {% endfor %}


    {% if object.stories %}

        {% for story in object.stories.all %}
            {% include "./storyCard.html" with story=story %}
        {% endfor %}

    {% else %}
        <p>There are no stories categorised as {{story.category_type}} </p>
     {% endif %}
    <!-- {% for category in categories %}
        <a href="#"><h3>{{ category }}</h3></a>
    {% endfor %} -->


</div>

{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
<div id="create-form">
    <form action= "" method="post">
        {% csrf_token %}
        {{form.media}}
        {{form.as_p}}
        <input type="submit" value="Submit" id="submit-button">
    </form>
</div>

{% else %}

<div id="createStory-text">
    <br><p> Please login or create an account to write a news story.</p>
    <a href="{% url 'login' %}">Login</a><br><br><br>
    <a href="{% url 'users:createAccount' %}">Create Account</a>
</div>

{% endif %}

{% endblock %}

she_codes_news/news/templates/news/delete.html
{% extends "base.html" %}
{% load static %}    

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
{% if user.is_authenticated and user == story.author %}
    <h2>Delete post</h2>
    <div id="delete-story-form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}

            Are you sure you want to delete the following post?:<br><br>

            <button type="submit" id="submit-button">Delete</button><br>
            <a href="{% url 'news:userStoryEdit' story.id %}">Cancel</a>
            <a href="{% url 'news:userStoryEdit' story.id %}">Edit</a>

        </form>
    </div>

    <div id="story-wrapper">
        <h2>{{ story.title }}</h2>
        <h4> 
            <a href="{% url 'news:userStory' story.author %}">{{story.author}}</a>
        </h4>
        <h4>Category:<a href="http://127.0.0.1:8000/news/filter/?category={{story.category}}">{{story.category}}</a></h4>

        <div id="story-content">
            <!-- <img src="{% static '/news/images/placeholder-5.jpg' %}"> -->
            {% if story.image_link|length != 0 %}
            <img src="{{ story.image_link }}">
                {% else %}
            <img src="https://picsum.photos/600">
            {% endif %}
            {{ story.content|linebreaks }}
        </div>
    </div>
{% else %}
    <a href="{% url 'login' %}">Please login or create an account to write/edit a news story.</a>
{% endif %}

{% endblock %}

she_codes_news/news/templates/news/edit.html
{% extends "base.html" %} {% load static %} {% block stylesheets %}

<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock %} {% block content %} {% if user.is_authenticated and user ==
story.author %}

<p><a href="{% url 'news:userStoryDelete' story.id %}">Delete</a></p>

<div id="edit-story-form">
  <h2>Edit post</h2>
  <form action="" method="post">
    {% csrf_token %} {{ form.media }} {{ form.as_p }}
    <button type="submit" id="edit-button">Save Changes</button>
  </form>
</div>

{% else %}
<a href="{% url 'login' %}"
  >Please login or create an account to write/edit a news story.</a
>
{% endif %} {% endblock %}

she_codes_news/news/templates/news/filter.html
{% extends "base.html" %}
{% load static %}    

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<div id="filter-auth"></div>
    {% if user.is_authenticated %}
    <a id="New-Story" href="{% url 'news:newsStory' %}">Write New Story</a>
    {% else %}
    <a href="{% url 'login' %}">Please login or create an account to write a news story.</a>
    {% endif %}
</div>

<div id=filter-script>
    <script>
        function goToNewPage() {
            if(document.getElementById('target').value){
                window.location.href = document.getElementById('target').value;
            }
        }
    </script>
    <form name="dropdown">
        <p><label for="id_q">Search:</label>
        <select name="selected" id="target" accesskey="E">
        <!-- <option selected>Select...</option> -->
        {% for x,y in form.fields.category.choices %}
            <option value="?category={{ x }}"{% if form.fields.category.value == x %} selected{% endif %}>{{ y }}</option>
        {% endfor %}  
        </select>
        <input type="button" value="Go" id="submit-button" onclick="goToNewPage(document.dropdown.selected)"></p>
    </form>
</div>



    

    {% if latest_stories %}
    <h2>Latest News</h2>
    <div id="latest-stories">
            {% for story in latest_stories %}
                <!-- <p>{{ story.title }}</p> -->
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
    </div>
{% endif %}
   

    <h2>All News</h2>
    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                <!-- <p>{{ story.title }}</p> -->
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}
          <!-- {% for category in Category_CHOICES %} -->
            <!-- <option value="{{category.id}}">{{category.name}}</option> -->
            <!-- {% endfor %} -->

she_codes_news/news/templates/news/filter3.html
{% extends "base.html" %}
{% load static %}    

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<div id="filter-auth"></div>
    {% if user.is_authenticated %}
    <a id="New-Story" href="{% url 'news:newsStory' %}">Write New Story</a>
    {% else %}
    <a href="{% url 'login' %}">Please login or create an account to write a news story.</a>
    {% endif %}
</div>

<div id=filter-script>
    <script>
        function goToNewPage() {
            if(document.getElementById('target').value){
                window.location.href = document.getElementById('target').value;
            }
        }
    </script>
    <form name="dropdown">
        <p><label for="id_q">Search:</label>
        <select name="selected" id="target" accesskey="E">
        <!-- <option selected>Select...</option> -->
        {% for x,y in form.fields.category.choices %}
            <option value="?category={{ x }}"{% if form.fields.category.value == x %} selected{% endif %}>{{ y }}</option>
        {% endfor %}  
        </select>
        <input type="button" value="Go" id="submit-button" onclick="goToNewPage(document.dropdown.selected)"></p>
    </form>
</div>



    

    {% if latest_stories %}
    <h2>Latest News</h2>
    <div id="latest-stories">
            {% for story in latest_stories %}
                <!-- <p>{{ story.title }}</p> -->
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
    </div>
{% endif %}
   

    <h2>All News</h2>
    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                <!-- <p>{{ story.title }}</p> -->
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}
          <!-- {% for category in Category_CHOICES %} -->
            <!-- <option value="{{category.id}}">{{category.name}}</option> -->
            <!-- {% endfor %} -->

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}    

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="index-text">

    <div id="index-auth">

        {% if user.is_authenticated %}
            <a id="New-Story" href="{% url 'news:newsStory' %}">Write New Story</a>
        {% else %}
            <a href="{% url 'login' %}">Please login or create an account to write a news story.</a><br><br>
        {% endif %}
    </div>

    <div id="filter-text">
        <p>Search by<a id="click-tag" href="{% url 'news:filter' %}">category</a><br></p>
            
        <p>View<a id="click-tag" href="{% url 'news:userList' %}"> authors</a></p>
    </div>
</div>

    <h2>Latest News</h2>
    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                <!-- <p>{{ story.title }}</p> -->
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% endif %}
    </div>


    <h2>All News</h2>
    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                <!-- <p>{{ story.title }}</p> -->
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}    

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    
    <div id="story-wrapper-text">

        <div id="story-wrapper-text-left">
            <h2>{{ story.title }}</h2>
            <!-- <h4>{{ story.author }}</h4> -->
            <p> 
                Author: <a id="click-tag" href="{% url 'news:userStory' story.author %}">{{story.author}}</a>
            </p>
            <!-- <p>Category: {{story.gender}}</a></p> -->
            <p>Category: <a id="click-tag" href='http://127.0.0.1:8000/news/filter/?category={{story.category}}'>{{story.category}} </a></p>
            <p>Published: {{story.pub_date}} </a></p>
        </div>

        <div id="story-wrapper-text-right">
            {% if user.is_authenticated and user == story.author %}
                <p><a id="click-tag" href="{% url 'news:userStoryEdit' story.id %}">Edit</a></p>
                <p><a id="click-tag" href="{% url 'news:userStoryDelete' story.id %}">Delete</a></p>
            {% endif %}
        </div>

    </div>
 
    <div id="story-content">
        <!-- <img src="{% static '/news/images/placeholder-5.jpg' %}"> -->
        {% if story.image_link|length != 0 %}
        <img src="{{ story.image_link }}">
            {% else %}
        <img src="https://picsum.photos/600">
        {% endif %}
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}
        <!-- <a href="{% url 'news:categoryStory' story.category_type %}">{{story.category_type}}</a></h4> -->

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image_link|length != 0 %}
        <img src = "{{ story.image_link }}">
            <!-- <img src="../static/news/images/placeholder-{{ position }}.jpg"> -->
            {% else %}
        <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.category }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/news/templates/news/user-list.html
{% extends 'base.html' %}
{% load static %}    

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}


<div>
    <p>Select the author you wish to view their stories.</p>
    <ul>
        {% for user_obj in object_list %}
        <li>
            <a href="{% url 'news:userStory' user_obj %}">{{user_obj}}</a>
        </li>
        {% endfor %}
    </ul>

</div>

{% endblock %}

she_codes_news/news/templates/news/user-story.html
{% extends "base.html" %}
{% load static %}    

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}



<div id="all-stories">
    {% if object.stories %}
    <div class="story-card", id="story-content">
        <h3>{{ object }}'s story page</h3>
        <p> Number of stories written by {{ object }}: {{object.stories.all|length}}! </p>

    </div>

        {% for story in object.stories.all %}
            {% include "./storyCard.html" with story=story %}
        {% endfor %}

    {% else %}

        <p>No stories have been written by {{object}}.</p>

    {% endif %}
</div>

{% endblock %}